import type { Metadata } from "next";
import { Roboto_Mono } from 'next/font/google'
import "./globals.css";

const inter = Roboto_Mono({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className={"antialiased"}>
          {children}
      </body>
    </html>
  );
}
